import { AppView, Language } from './types';
import type { ReactNode } from 'react';

export const ICONS: { [key: string]: ReactNode } = {
  microphone: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z"></path><path d="M19 10v2a7 7 0 0 1-14 0v-2"></path><line x1="12" x2="12" y1="19" y2="22"></line></svg>,
  stop: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect width="18" height="18" x="3" y="3" rx="2"></rect></svg>,
  chat: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg>,
  map: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="1 6 1 22 8 18 16 22 23 18 23 2 16 6 8 2 1 6"></polygon><line x1="8" x2="8" y1="2" y2="18"></line><line x1="16" x2="16" y1="6" y2="22"></line></svg>,
  upload: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="17 8 12 3 7 8"></polyline><line x1="12" x2="12" y1="3" y2="15"></line></svg>,
  send: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="22" x2="11" y1="2" y2="13"></line><polygon points="22 2 15 22 11 13 2 9 22 2"></polygon></svg>,
  volume: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"></polygon><path d="M15.54 8.46a5 5 0 0 1 0 7.07"></path></svg>,
  home: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>,
  user: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>,
  bot: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 8V4H8"></path><rect width="16" height="12" x="4" y="8" rx="2"></rect><path d="M2 14h2"></path><path d="M20 14h2"></path><path d="M15 13v2"></path><path d="M9 13v2"></path></svg>,
  pulse: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 12h-4l-3 9L9 3l-3 9H2"></path></svg>,
  stethoscope: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4.8 2.3A.3.3 0 1 0 5.4 2a.3.3 0 0 0-.6.3zM8.3 2.3A.3.3 0 1 0 7.7 2a.3.3 0 0 0 .6.3zM5 3v2.3c0 1.4 1.1 2.5 2.5 2.5h.3c.3 0 .6-.1.8-.4l1.8-2.6c.2-.3.1-.7-.2-1l-1-1.4c-.2-.2-.5-.3-.8-.3H5zm3.5 0H10c.3 0 .6.1.8.4l1.8 2.6c.2.2.1.6-.2.8l-1 1.5c-.2.2-.5.3-.8.3H7.5C6.1 8.1 5 7 5 5.6V3h3.5z"></path><path d="M12 9.5c2.3 0 4.2-1.9 4.2-4.2V3h-1v2.2c0 1.8-1.4 3.2-3.2 3.2s-3.2-1.4-3.2-3.2V3h-1v2.2c0 2.4 1.9 4.3 4.2 4.3zM4 11.8v6.5c0 1.5 1.2 2.7 2.7 2.7h10.6c1.5 0 2.7-1.2 2.7-2.7v-6.5c2.5-1.3 2.5-4.8 0-6C18.2 5 15.2 4.3 12 4.3S5.8 5 4 5.8c-2.5 1.2-2.5 4.7 0 6z"></path></svg>,
  medicine: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M15 8.5h3.5a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H3.5a2 2 0 0 1-2-2v-10a2 2 0 0 1 2-2H6.5"></path><line x1="8" x2="16" y1="1" y2="1"></line><line x1="7" x2="7" y1="1" y2="5"></line><line x1="17" x2="17" y1="1" y2="5"></line><line x1="7" x2="17" y1="5" y2="5"></line></svg>,
  emergency: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" x2="12" y1="8" y2="16"></line><line x1="8" x2="16" y1="12" y2="12"></line></svg>,
  video: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="23 7 16 12 23 17 23 7"></polygon><rect width="15" height="14" x="1" y="5" rx="2" ry="2"></rect></svg>,
};

export const TEXTS: { [key in Language]: { [key: string]: string } } = {
  [Language.EN]: {
    appName: "Sehat",
    tagline: "Rural Telemedicine Access",
    chatbot: "Health Chatbot",
    chatbotDesc: "Talk to an AI health assistant with voice or text.",
    findCare: "Find Care",
    findCareDesc: "Locate nearby hospitals and pharmacies.",
    analyzeReport: "Health Record",
    analyzeReportDesc: "Save or upload a health record to the patient profile.",
    symptomAnalyzer: "Symptom Analyzer",
    symptomAnalyzerDesc: "AI-powered diagnostic suggestions for doctors.",
    selectLanguage: "Select Language",
    startConsultation: "Start Voice Consultation",
    stopConsultation: "Stop Consultation",
    connecting: "Connecting...",
    listening: "Listening...",
    speakNow: "Speak now...",
    modelSpeaking: "Assistant is speaking...",
    yourQuestion: "Your question...",
    typeMessage: "Type your message...",
    askLocation: "Ask for nearby hospitals, clinics, etc.",
    search: "Search",
    gettingLocation: "Getting your location...",
    locationError: "Could not get location. Please enable location services.",
    uploadPrompt: "Upload a lab report or prescription",
    analyze: "Analyze",
    analysisResult: "Analysis Result",
    listeningTo: "Listening to:",
    home: "Home",
    disclaimer: "Disclaimer: This tool provides potential suggestions based on AI analysis and is intended for use by qualified medical professionals only. It is not a substitute for a professional medical diagnosis.",
    enterSymptoms: "Enter patient symptoms here (e.g., '45-year-old male with persistent cough, fever, and shortness of breath for 3 days').",
    analyzeSymptoms: "Analyze Symptoms",
    analysisResults: "Potential Diagnoses",
    medicineFinder: "Medicine Availability",
    medicineFinderDesc: "Find nearby pharmacies and medicine stock.",
    emergencySOS: "Emergency SOS",
    emergencySOSDesc: "Quick access to emergency numbers and nearby hospitals.",
    videoConsult: "Video Consult",
    videoConsultDesc: "Video consultation with healthcare providers.",
  },
  [Language.HI]: {
    appName: "Sehat — कल्याण",
    tagline: "ग्रामीण टेलीमेडिसिन एक्सेस",
    chatbot: "एआई हेल्थ चैटबोट",
    chatbotDesc: "एआई स्वास्थ्य सहायक से आवाज़ या टेक्स्ट में बात करें।",
    findCare: "देखभाल खोजें",
    findCareDesc: "आस-पास के अस्पताल और फार्मेसियों का पता लगाएं।",
    analyzeReport: "हेल्थ रिकॉर्ड",
    analyzeReportDesc: "रोगी प्रोफ़ाइल में हेल्थ रिकॉर्ड सेव/अपलोड करें।",
    symptomAnalyzer: "लक्षण विश्लेषक",
    symptomAnalyzerDesc: "डॉक्टरों के लिए एआई-संचालित नैदानिक सुझाव।",
    selectLanguage: "भाषा चुनें",
    startConsultation: "वॉयस परामर्श शुरू करें",
    stopConsultation: "परामर्श रोकें",
    connecting: "कनेक्ट हो रहा है...",
    listening: "सुन रहा है...",
    speakNow: "अब बोलें...",
    modelSpeaking: "सहायक बोल रहा है...",
    yourQuestion: "आपका सवाल...",
    typeMessage: "अपना संदेश लिखें...",
    askLocation: "आस-पास के अस्पताल, क्लिनिक आदि के लिए पूछें।",
    search: "खोजें",
    gettingLocation: "आपका स्थान प्राप्त हो रहा है...",
    locationError: "स्थान प्राप्त नहीं हो सका। कृपया स्थान सेवाएं सक्षम करें।",
    uploadPrompt: "एक लैब रिपोर्ट या नुस्खा अपलोड करें",
    analyze: "विश्लेषण करें",
    analysisResult: "विश्लेषण परिणाम",
    listeningTo: "सुन रहा है:",
    home: "होम",
    disclaimer: "अस्वीकरण: यह उपकरण एआई विश्लेषण पर आधारित संभावित सुझाव प्रदान करता है और केवल योग्य चिकित्सा पेशेवरों द्वारा उपयोग के लिए है। यह एक पेशेवर चिकित्सा निदान का विकल्प नहीं है।",
    enterSymptoms: "रोगी के लक्षण यहाँ दर्ज करें (उदाहरण के लिए, '45 वर्षीय पुरुष को 3 दिनों से लगातार खांसी, बुखार और सांस लेने में तकलीफ है')...",
    analyzeSymptoms: "लक्षणों का विश्लेषण करें",
    analysisResults: "संभावित निदान",
    medicineFinder: "दवा उपलब्धता",
    medicineFinderDesc: "पास की फार्मेसियों और दवा स्टॉक खोजें।",
    emergencySOS: "आपातकालीन एसओएस",
    emergencySOSDesc: "आपातकालीन नंबर और पास के अस्पतालों तक तीव्र पहुंच।",
    videoConsult: "वीडियो परामर्श",
    videoConsultDesc: "स्वास्थ्य सेवा प्रदाताओं के साथ वीडियो परामर्श।",
  },
  [Language.PA]: {
    appName: "Sehat — ਖੈਰਤੀ",
    tagline: "ਪੇਂਡੂ ਟੈਲੀਮੈਡੀਸਨ ਪਹੁੰਚ",
    chatbot: "ਏਆਈ ਹੈਲਥ ਚੈਟਬੋਟ",
    chatbotDesc: "ਏਆਈ ਸਿਹਤ ਸਹਾਇਕ ਨਾਲ ਆਵਾਜ਼ ਜਾਂ ਲਿਖਤ ਵਿੱਚ ਗੱਲ ਕਰੋ।",
    findCare: "ਦੇਖਭਾਲ ਲੱਭੋ",
    findCareDesc: "ਨੇੜਲੇ ਹਸਪਤਾਲਾਂ ਅਤੇ ਫਾਰਮੇਸੀਆਂ ਦਾ ਪਤਾ ਲਗਾਓ।",
    analyzeReport: "ਹੈਲਥ ਰਿਕਾਰਡ",
    analyzeReportDesc: "ਰੋਗੀ ਪ੍ਰੋਫਾਈਲ ਵਿੱਚ ਹੈਲਥ ਰਿਕਾਰਡ ਸੇਵ/ਅਪਲੋਡ ਕਰੋ।",
    symptomAnalyzer: "ਲੱਛਣ ਵਿਸ਼ਲੇਸ਼ਕ",
    symptomAnalyzerDesc: "ਡਾਕਟਰਾਂ ਲਈ ਏਆਈ-ਸੰਚਾਲਿਤ ਡਾਇਗਨੌਸਟਿਕ ਸੁਝਾਅ।",
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    startConsultation: "ਵੌਇਸ ਸਲਾਹ ਸ਼ੁਰੂ ਕਰੋ",
    stopConsultation: "ਸਲਾਹ ਰੋਕੋ",
    connecting: "ਕਨੈਕਟ ਹੋ ਰਿਹਾ ਹੈ...",
    listening: "ਸੁਣ ਰਿਹਾ ਹੈ...",
    speakNow: "ਹੁਣ ਬੋਲੋ...",
    modelSpeaking: "ਸਹਾਇਕ ਬੋਲ ਰਿਹਾ ਹੈ...",
    yourQuestion: "ਤੁਹਾਡਾ ਸਵਾਲ...",
    typeMessage: "ਆਪਣਾ ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...",
    askLocation: "ਨੇੜਲੇ ਹਸਪਤਾਲਾਂ, ਕਲੀਨਿਕਾਂ, ਆਦਿ ਲਈ ਪੁੱਛੋ।",
    search: "ਖੋਜ",
    gettingLocation: "ਤੁਹਾਡਾ ਸਥਾਨ ਪ੍ਰਾਪਤ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    locationError: "ਸਥਾਨ ਪ੍ਰਾਪਤ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਸਥਾਨ ਸੇਵਾਵਾਂ ਨੂੰ ਸਮਰੱਥ ਕਰੋ।",
    uploadPrompt: "ਇੱਕ ਲੈਬ ਰਿਪੋਰਟ ਜਾਂ ਨੁਸਖ਼ਾ ਅੱਪਲੋਡ ਕਰੋ",
    analyze: "ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
    analysisResult: "ਵਿਸ਼ਲੇਸ਼ਣ ਨਤੀਜਾ",
    listeningTo: "ਸੁਣ ਰਿਹਾ ਹੈ:",
    home: "ਹੋਮ",
    disclaimer: "ਬੇਦਾਅਵਾ: ਇਹ ਟੂਲ ਏਆਈ ਵਿਸ਼ਲੇਸ਼ਣ 'ਤੇ ਅਧਾਰਤ ਸੰਭਾਵੀ ਸੁਝਾਅ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ ਅਤੇ ਸਿਰਫ ਯੋਗ ਮੈਡੀਕਲ ਪੇਸ਼ੇਵਰਾਂ ਦੁਆਰਾ ਵਰਤੋਂ ਲਈ ਹੈ। ਇਹ ਇੱਕ ਪੇਸ਼ੇਵਰ ਡਾਕਟਰੀ ਨਿਦਾਨ ਦਾ ਬਦਲ ਨਹੀਂ ਹੈ।",
    enterSymptoms: "ਮਰੀਜ਼ ਦੇ ਲੱਛਣ ਇੱਥੇ ਦਰਜ ਕਰੋ (ਜਿਵੇਂ ਕਿ, '45-ਸਾਲਾ ਮਰਦ ਨੂੰ 3 ਦਿਨਾਂ ਤੋਂ ਲਗਾਤਾਰ ਖੰਘ, ਬੁਖਾਰ ਅਤੇ ਸਾਹ ਚੜ੍ਹ ਰਿਹਾ ਹੈ')...",
    analyzeSymptoms: "ਲੱਛਣਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
    analysisResults: "ਸੰਭਾਵੀ ਨਿਦਾਨ",
    medicineFinder: "ਦਵਾ ਉਪਲਬਧਤਾ",
    medicineFinderDesc: "ਨੇੜਲੀਆਂ ਫਾਰਮੇਸੀਆਂ ਅਤੇ ਦਵਾ ਸਟਾਕ ਖੋਜੋ।",
    emergencySOS: "ਐਮਰਜੈਂਸੀ ਐਸ.ਓ.ਐਸ.",
    emergencySOSDesc: "ਐਮਰਜੈਂਸੀ ਨੰਬਰ ਅਤੇ ਨੇੜਲੇ ਹਸਪਤਾਲਾਂ ਤੱਕ ਤੇਜ਼ ਪਹੁੰਚ।",
    videoConsult: "ਵਿਡੀਓ ਸਲਾਹ",
    videoConsultDesc: "ਸਵਾਸਥ ਸਿਵਾ ਪ੍ਰਦਾਤਾਵਾਂ ਨਾਲ ਵਿਡੀਓ ਸਲਾਹ।",
  },
};

export const NAV_ITEMS: { view: AppView; icon: ReactNode; textKey: keyof typeof TEXTS[Language.EN] }[] = [
    { view: AppView.CHATBOT, icon: ICONS.chat, textKey: 'chatbot' },
    { view: AppView.MEDICINE, icon: ICONS.medicine, textKey: 'medicineFinder' },
    { view: AppView.FIND_CARE, icon: ICONS.map, textKey: 'findCare' },
    { view: AppView.ANALYZE_REPORT, icon: ICONS.upload, textKey: 'analyzeReport' },
    { view: AppView.EMERGENCY, icon: ICONS.emergency, textKey: 'emergencySOS' },
    { view: AppView.VIDEO_CONSULT, icon: ICONS.video, textKey: 'videoConsult' },
];
