import { Language, AppView } from './types';

// Icon components as simple strings (can be replaced with actual icons)
export const ICONS = {
  bot: '🤖',
  send: '➤',
  home: '🏠',
  map: '📍',
  upload: '📤',
  chat: '💬',
  emergency: '🚨',
  video: '📹',
  medicine: '💊',
};

// Navigation items
export const NAV_ITEMS = [
  {
    view: AppView.DASHBOARD,
    icon: ICONS.home,
    textKey: 'dashboard',
  },
  {
    view: AppView.CHATBOT,
    icon: ICONS.chat,
    textKey: 'chatbot',
  },
  {
    view: AppView.FIND_CARE,
    icon: ICONS.medicine,
    textKey: 'findCare',
  },
];

// Text content for different languages
export const TEXTS: { [key in Language]: { [key: string]: string } } = {
  [Language.EN]: {
    appName: 'Arogya Manthan',
    tagline: 'Your AI Health Assistant',
    dashboard: 'Dashboard',
    chatbot: 'Health Chat',
    chatbotDesc: 'Discuss your symptoms with our AI assistant',
    findCare: 'Find Medicine',
    findCareDesc: 'Find nearby pharmacies and check medicine availability',
    loginTitle: 'Welcome to Arogya Manthan',
    loginSubtitle: 'Your personal AI health assistant',
    phoneLabel: 'Phone Number',
    phonePlaceholder: 'Enter your phone number',
    nameLabel: 'Name',
    namePlaceholder: 'Enter your name',
    loginButton: 'Get Started',
    disclaimer: 'This tool provides diagnostic suggestions based on local AI analysis and is intended for informational purposes only. Always consult a healthcare professional for proper diagnosis and treatment.',
    typeMessage: 'Type your symptoms here...',
    error: 'Error',
    askLocation: 'Search for healthcare facilities...',
    locationError: 'Unable to get location. Please enable location services.',
    gettingLocation: 'Getting your location...',
    uploadPrompt: 'Drop your medical report here or click to upload',
    analyze: 'Analyze Report',
    analysisResult: 'Analysis Result',
    enterSymptoms: 'Enter your symptoms...',
    analyzeSymptoms: 'Analyze Symptoms',
    analysisResults: 'Analysis Results',
  },
  [Language.HI]: {
    appName: 'Arogya Manthan',
    tagline: 'आपका AI स्वास्थ्य सहायक',
    dashboard: 'डैशबोर्ड',
    chatbot: 'स्वास्थ्य चैट',
    chatbotDesc: 'अपने लक्षणों पर चर्चा करें',
    findCare: 'दवा खोजें',
    findCareDesc: 'पास की फार्मेसियां खोजें और दवा की उपलब्धता जांचें',
    loginTitle: 'Arogya Manthan में आपका स्वागत है',
    loginSubtitle: 'आपका व्यक्तिगत AI स्वास्थ्य सहायक',
    phoneLabel: 'फोन नंबर',
    phonePlaceholder: 'अपना फोन नंबर दर्ज करें',
    nameLabel: 'नाम',
    namePlaceholder: 'अपना नाम दर्ज करें',
    loginButton: 'शुरू करें',
    disclaimer: 'यह उपकरण स्थानीय AI विश्लेषण के आधार पर निदान सुझाव प्रदान करता है और केवल सूचना के उद्देश्यों के लिए है। उचित निदान और उपचार के लिए हमेशा स्वास्थ्य पेशेवर से परामर्श करें।',
    typeMessage: 'अपने लक्षण यहां लिखें...',
    error: 'त्रुटि',
    askLocation: 'स्वास्थ्य सेवाएं खोजें...',
    locationError: 'स्थान प्राप्त करने में असमर्थ। कृपया स्थान सेवाएं सक्षम करें।',
    gettingLocation: 'आपका स्थान प्राप्त कर रहे हैं...',
    uploadPrompt: 'अपनी चिकित्सा रिपोर्ट यहां छोड़ें या अपलोड करने के लिए क्लिक करें',
    analyze: 'विश्लेषण करें',
    analysisResult: 'विश्लेषण परिणाम',
    enterSymptoms: 'अपने लक्षण दर्ज करें...',
    analyzeSymptoms: 'लक्षणों का विश्लेषण करें',
    analysisResults: 'विश्लेषण परिणाम',
  },
  [Language.PA]: {
    appName: 'Arogya Manthan',
    tagline: 'Your AI Health Assistant',
    dashboard: 'Dashboard',
    chatbot: 'Health Chat',
    chatbotDesc: 'Discuss your symptoms with our AI assistant',
    findCare: 'Find Hospital',
    findCareDesc: 'Find nearby pharmacies and check medicine availability',
    loginTitle: 'Welcome to Arogya Manthan',
    loginSubtitle: 'Your personal AI health assistant',
    phoneLabel: 'Phone Number',
    phonePlaceholder: 'Enter your phone number',
    nameLabel: 'Name',
    namePlaceholder: 'Enter your name',
    loginButton: 'Get Started',
    disclaimer: 'This tool provides diagnostic suggestions based on local AI analysis and is intended for informational purposes only. Always consult a healthcare professional for proper diagnosis and treatment.',
    typeMessage: 'Type your symptoms here...',
    error: 'Error',
    askLocation: 'Search for healthcare facilities...',
    locationError: 'Unable to get location. Please enable location services.',
    gettingLocation: 'Getting your location...',
    uploadPrompt: 'Drop your medical report here or click to upload',
    analyze: 'Analyze Report',
    analysisResult: 'Analysis Result',
    enterSymptoms: 'Enter your symptoms...',
    analyzeSymptoms: 'Analyze Symptoms',
    analysisResults: 'Analysis Results',
  },
};

